### ISSUE TITLE
Como instalar no Telegram do meu grupo?

### ISSUE THREAD

**Issue by woliveiras** [linuxsoares/bot-status-metro#1]
Mano, faltou deixar na documentação como instalar o bot. ❤️

**Comment by linuxsoares** [comment]
Para adicionar o bot no grupo, é só adicionar o usuário `@metro_status_bot`

**Comment by woliveiras** [comment]
Atualizei a documentação, mano https://github.com/linuxsoares/bot-status-metro/pulls
